### ISSUE TITLE
django project with this lib starting block

### ISSUE THREAD

**Issue by ray1888** [opentracing-contrib/python-django#11]
![image](https://user-images.githubusercontent.com/19427008/34243465-d9f6129c-e65b-11e7-9003-32b479262077.png)
i start my app as above ,and it just get stuck with no Exception traceback,so where is the problem,
my code modify as your README.md,like this .
```
import django_opentracing
from jaeger_client import Config

config = Config(
        config={ # usually read from some yaml config
            'sampler': {
                'type': 'const',
                'param': 1,
            },
            'logging': True,
        },
        service_name='OpsManange')
# OpenTracing settings

# if not included, defaults to False
# has to come before OPENTRACING_TRACER setting because python...
OPENTRACING_TRACE_ALL = False,

# defaults to []
# only valid if OPENTRACING_TRACE_ALL == True
OPENTRACING_TRACED_ATTRIBUTES = ['arg1', 'arg2'],
open_tracer = config.initialize_tracer()
OPENTRACING_TRACER = django_opentracing.DjangoTracer(open_tracer)

```

**Comment by ray1888** [comment]
but when i no initializing the tracer , that is worked. so tricky.
![image](https://user-images.githubusercontent.com/19427008/34243613-8a8cdf6e-e65c-11e7-9fc4-af7fe6878344.png)

**Comment by ray1888** [comment]
and i have already change the lib with mike bryant in PR#9 code , it still doesn't work

**Comment by ray1888** [comment]
the exception is below . can u help me to find what is the problem , because the attr is a  string host as you fixed in you PR @Mike Bryant

![image](https://user-images.githubusercontent.com/19427008/34291139-d608b236-e735-11e7-8e01-3c37e45b3769.png)

**Comment by ray1888** [comment]
@mikebryant

**Comment by ray1888** [comment]
but when i try to Commented out code in app/setting.py
```
OPENTRACING_TRACER_PARAMETERS = {
   # 'host': 'collector',
}
```
django is starting .but when i reach the '/ ' , it get an other exception , which is not exist before using the django-opentracing 
![image](https://user-images.githubusercontent.com/19427008/34291372-f45a7a02-e736-11e7-9fe4-e79283b23bc3.png)

**Comment by mikebryant** [comment]
@ray1888 The example parameters are just that, you'd need to replace `host` with any parameters your particular Tracer implementation needs.

After you've commented it out - there's no references to `host` anywhere else in the codebase, so I've no clue where that could be coming from. So - are you sure you've saved the file, and restarted the runserver?

**Comment by mikebryant** [comment]
For Jaeger this is how I have it configured (as the Jaeger client needs two passes of initialization, you need to provide your own callable): https://github.com/opentracing-contrib/python-django/pull/9#issuecomment-353110261

**Comment by mikebryant** [comment]
(Also see https://github.com/jaegertracing/jaeger-client-python#production)

**Comment by mikebryant** [comment]
How about trying these settings?
```
OPENTRACING_TRACE_ALL = False,

OPENTRACING_TRACER_CALLABLE = __name__ + '.tracer'

def tracer():
    from jaeger_client import Config
    config = Config(
        config={ # usually read from some yaml config
            'sampler': {
                'type': 'const',
                'param': 1,
            },
            'logging': True,
        },
        service_name='OpsManange')
    return config.initialize_tracer()
```

**Comment by ray1888** [comment]
i haven't try the setting above , i try it later. i think this should be worked?(or may be not)

**Comment by ray1888** [comment]
thanks, i found where the problem is . It's becauase the comma i add in the setting.py, turn OPENTRACING_TRACED_ATTRIBUTES = ['arg1', 'arg2'], is reading config to a tuple.

**Comment by ray1888** [comment]
it work because it haven't init tracer, when i init the tracer , it stuck again @mikebryant , the no exception throw , so where is the problem
```
#settings.py
def tracer():
    from jaeger_client import Config
    config = Config(
        config={ 
            'sampler': {
                'type': 'const',
                'param': 1,
            },
            'logging': True,
        },
        service_name='OpsManange')
    return config.initialize_tracer()
 
OPENTRACING_TRACER = django_opentracing.DjangoTracer(tracer())
```

**Comment by ray1888** [comment]
my project tree is like this 
```
├── demo_imgs
├── LICENSE
├── manage.py
├── OpsManage
│   ├── asgi.py
│   ├── consumers.py
│   ├── consumers.pyc
│   ├── data
│   │   ├── base.py
│   │   ├── base.pyc
│   │   ├── DsMySQL.py
│   │   ├── DsMySQL.pyc
│   │   ├── DsRedisOps.py
│   │   ├── DsRedisOps.pyc
│   │   ├── __init__.py
│   │   └── __init__.pyc
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── interactive.py
│   ├── interactive.pyc
│   ├── models.py
│   ├── models.pyc
│   ├── restfull(folder)
│   ├── routing.py
│   ├── routing.pyc
│   ├── serializers.py
│   ├── serializers.pyc
│   ├── settings.py
...
```

**Comment by mikebryant** [comment]
The problem is your `OPENTRACING_TRACER` line. Remove it, as I said earlier. As it says in the readme in my PR, it can cause problems, for example, the problem you're having.
The point of my PR is to do that for you, on demand

**Comment by mikebryant** [comment]
Actually, thinking about it, you also want `OPENTRACING_TRACE_ALL = True`

**Comment by ray1888** [comment]
remove the line you mention is get it started , but it can't sent any package out . i think is maybe the tracer is not initialzie? 
![image](https://user-images.githubusercontent.com/19427008/34324102-805e9cfe-e89f-11e7-9077-90bcc97c0be3.png)

tcpdump packet is nothing 
![image](https://user-images.githubusercontent.com/19427008/34324103-96521ea0-e89f-11e7-980a-90224743a90b.png)
is my initialize way is wrong? because the project i get , is only has project_name/setting, the code was written is project_name folder . so do i need to change the way i initialize the tracer way?
```
##the full  settings.py is 
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ['json', 'pickle']
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24
CELERYD_MAX_TASKS_PER_CHILD = 40
CELERY_TRACK_STARTED = True
CELERY_TIMEZONE='Asia/Shanghai'
platforms.C_FORCE_ROOT = True
 
REDSI_KWARGS_LPUSH = {"host":'192.168.0.253','port':6379,'db':3}
REDSI_LPUSH_POOL = None
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kd8f&jx1h^1m-uldfdo3d#10d9mbc-ijjz!tozusy@aw#h+875'
 
# if not included, defaults to False
# has to come before OPENTRACING_TRACER setting because python...
OPENTRACING_TRACE_ALL = True,
 
# defaults to []
# only valid if OPENTRACING_TRACE_ALL == True          
OPENTRACING_TRACED_ATTRIBUTES = ['host']
 
# Callable that returns an `opentracing.Tracer` implementation.
OPENTRACING_TRACER_CALLABLE = 'opentracing.Tracer'
#OPENTRACING_TRACER_CALLABLE = __name__ + '.tracer'
 
# Parameters for the callable (Depending on the tracer implementation chosen)
OPENTRACING_TRACER_PARAMETERS = {
    #'host':'Ops',
}
 
#def tracer():
#    from jaeger_client import Config
#    return Config(config={}, service_name='test').initialize_tracer()
 
def tracer():
    from jaeger_client import Config
    config = Config(
        config={ 
            'sampler': {
                'type': 'const',
                'param': 1,
            },
            'logging': True,OPENTRACING_TRACED_ATTRIBUTES = ['host']
 
# Callable that returns an `opentracing.Tracer` implementation.
OPENTRACING_TRACER_CALLABLE = 'opentracing.Tracer'
#OPENTRACING_TRACER_CALLABLE = __name__ + '.tracer'
 
# Parameters for the callable (Depending on the tracer implementation chosen)
OPENTRACING_TRACER_PARAMETERS = {
    #'host':'Ops',
}
 
#def tracer():
#    from jaeger_client import Config
#    return Config(config={}, service_name='test').initialize_tracer()
 
def tracer():
    from jaeger_client import Config
    config = Config(
        config={ 
            'sampler': {
                'type': 'const',
                'param': 1,
            },
            'logging': True,              },
        service_name='OpsManange')
    return config.initialize_tracer()
 
 
#OPENTRACING_TRACER = django_opentracing.DjangoTracer(tracer()),
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
 
ALLOWED_HOSTS = ['*']
 

```

**Comment by mikebryant** [comment]
You will also want the `MIDDLEWARE` setting configured, including the opentracing niddleware

**Comment by mikebryant** [comment]
... And you seem to be have commented out the  line you need to configure it properly: `#OPENTRACING_TRACER_CALLABLE = __name__ + '.tracer'`

**Comment by mikebryant** [comment]
@ray1888 I've just put together this for you: https://github.com/mikebryant/opentracing-python-django-jaeger-example/tree/master/example

It's a worked example of how to configure django opentracing with Jaeger, I've just run it locally and it works for me.

**Comment by ray1888** [comment]
OK，i try it  now, thanks alot

**Comment by ray1888** [comment]
it works. i think is the sequential of the settings.py affect why it can't create record. fully appreciate for your help
