### ISSUE TITLE
Release 0.1.17 to pypi

### ISSUE THREAD

**Issue by benjigoldberg** [opentracing-contrib/python-django#13]
0.1.17 is cut here on GitHub but is unavailable on PyPi: https://pypi.python.org/pypi/django_opentracing

**Comment by mikebryant** [comment]
I've merged the changes I had for automatic releasing to Pypi.

This means 0.1.18 is now available. It has no changes over 0.1.17 besides packaging.

Is that suitable for you? :)

**Comment by benjigoldberg** [comment]
Perfect! 👌 

thanks!
