### ISSUE TITLE
'OpenTracingMiddleware' object has no attribute 'get_response'

### ISSUE THREAD

**Issue by ror6ax** [opentracing-contrib/python-django#24]
I'm getting an error saying `'OpenTracingMiddleware' object has no attribute 'get_response'` after enabling OT middleware.

**Comment by carlosalberto** [comment]
That's weird. `get_response` is provided by Django itself to the middleware - and for older version is shouldn't happen, as it is anyway an optional parameter. I will try tomorrow with an older version (tried with 1.10.x here).

Could you provide a small test case and the version of Django you are using? Or are you simply using one of the examples?

**Comment by carlosalberto** [comment]
Closing this issue for now - feel free to reopen if you think this error is still happening ;)
