### ISSUE TITLE
opentracing 2.x support

### ISSUE THREAD

**Issue by SEJeff** [opentracing-contrib/python-django#28]
Now that opentracing 2.x support is out, it would be nice to use it with this library.

**Comment by carlosalberto** [comment]
@SEJeff Oh, definitely. I've been working on porting the Tornado client (probably the trickiest one, as it uses coroutines and needs special care), and after that I will work on the Django support (hope to work on other items, such as #23 )

I will leave this item open for the time being as a reminder ;)

**Comment by carlosalberto** [comment]
Closing this one as #40 (with the OT 2.0 integration) has been merged an released ;)
