### ISSUE TITLE
Upgrade OT dependency to 2.2.0

### ISSUE THREAD

**Issue by jan25** [opentracing-contrib/python-django#49]
Jaeger_client latest (`4.0.0`) requires `opentracing <3.0,>=2.1`. This conflicts with django_opentracing latest (`1.0.1`) which requires `opentracing<2.1,>=2.0`.

Is it safe to upgrade OT dependency to `2.2.0`?

Similar issue with flask: https://github.com/opentracing-contrib/python-flask/issues/33

**Comment by Jamim** [comment]
Hello @jan25,

> Is it safe to upgrade OT dependency to `2.2.0`?

[It looks so](https://travis-ci.org/opentracing-contrib/python-django/builds/534370594).

**Comment by carlosalberto** [comment]
Closing this Issue, as #53 addressed it. Thanks!

**Comment by bj00rn** [comment]
@carlosalberto can we expect a release of this?

cheers!

**Comment by carlosalberto** [comment]
Forgot to mention here that I released last week ;)
