### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by Jamim** [opentracing-contrib/python-django#54]
Hi folks,

This project looks abandoned.
Is there a chance that PRs will be processed in the near future?

Best regards!

cc @carlosalberto, @yurishkuro

**Comment by carlosalberto** [comment]
Hey @Jamim 

No, it's not, it's only we have been spending lots of time in the new OpenTelemetry changes ;) But I will do a pass today over the existing PRs. Thanks for the reminder!

**Comment by Jamim** [comment]
Hello @carlosalberto,
Thank you for the hard work!
